version: '3.8'

services:
  certa-app:
    image: judyandiealvarez/certa:main
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=10.11.2.11;Database=certa;Username=certa;Password=certa123;Port=5432
    networks:
      - certa-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - certa_logs:/app/logs
      - certa_keys:/app/ca-keys

networks:
  certa-network:
    driver: overlay
    attachable: true

volumes:
  certa_logs:
    driver: trajano/glusterfs-volume-plugin
    driver_opts:
      volume: certa_logs
  certa_keys:
    driver: trajano/glusterfs-volume-plugin
    driver_opts:
      volume: certa_keys
