name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: judyandiealvarez/certa

jobs:
  build-and-push:
    runs-on: docker-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CertA/CertA.csproj

      - name: Build application
        run: dotnet build CertA/CertA.csproj --no-restore

      - name: Run tests
        run: dotnet test CertA/CertA.csproj --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:main -f CertA/Dockerfile .

      - name: Push to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:main

  deploy:
    runs-on: swarm
    needs: build-and-push
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME }}:main

      - name: Deploy to Swarm
        run: docker stack deploy -c docker-compose.swarm.yml certa

      - name: Wait for services
        run: sleep 30

      - name: Health check
        run: |
          SERVICE_NODE=$(docker stack ps certa --format "table {{.Node}}" | grep -v "NODE" | head -1)
          curl -f http://$SERVICE_NODE:8080

      - name: Show deployment status
        run: docker stack services certa
