name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: judyandiealvarez/certa

jobs:
  ci-cd:
    runs-on: swarm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Complete CI/CD Pipeline
        run: |
          echo "Starting complete CI/CD pipeline..."
          
          # Set up .NET
          echo "Setting up .NET..."
          dotnet --version
          
          # Security scan, build, test, and deploy all in one
          echo "Running security scan, build, test, and deploy..."
          
          # Build and test
          dotnet restore CertA/CertA.csproj
          dotnet build CertA/CertA.csproj --no-restore
          dotnet test CertA/CertA.csproj --no-build --verbosity normal
          
          # Build Docker image
          echo "Building Docker image..."
          docker build -t ${{ env.IMAGE_NAME }}:main -f CertA/Dockerfile .
          
          # Deploy to Swarm
          echo "Deploying to Swarm..."
          if docker stack ls | grep -q "certa"; then
            echo "Updating existing stack..."
            docker stack deploy -c docker-compose.swarm.yml certa
          else
            echo "Creating new stack..."
            docker stack deploy -c docker-compose.swarm.yml certa
          fi
          
          # Wait and check
          echo "Waiting for services..."
          sleep 30
          
          # Health check
          echo "Performing health check..."
          SERVICE_NODE=$(docker stack ps certa --format "table {{.Node}}" | grep -v "NODE" | head -1)
          HEALTH_CHECK_URL="http://$SERVICE_NODE:8080"
          
          for i in {1..10}; do
            if curl -f -s --connect-timeout 10 "$HEALTH_CHECK_URL" > /dev/null 2>&1; then
              echo "✅ Deployment successful! Application is responding."
              docker stack services certa
              exit 0
            else
              echo "Attempt $i/10: Health check failed, retrying..."
              sleep 15
            fi
          done
          
          echo "❌ Deployment failed - health check timeout"
          docker stack ps certa
          exit 1
