name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: judyandiealvarez/certa

jobs:
  ci-cd:
    runs-on: swarm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Complete CI/CD Pipeline
        run: dotnet restore CertA/CertA.csproj && dotnet build CertA/CertA.csproj --no-restore && dotnet test CertA/CertA.csproj --no-build --verbosity normal && docker build -t ${{ env.IMAGE_NAME }}:main -f CertA/Dockerfile . && docker stack deploy -c docker-compose.swarm.yml certa && sleep 30 && curl -f http://$(docker stack ps certa --format "table {{.Node}}" | grep -v "NODE" | head -1):8080
