name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: judyandiealvarez/certa

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CertA/CertA.csproj

      - name: Build application
        run: dotnet build CertA/CertA.csproj --no-restore

      - name: Run tests
        run: dotnet test CertA/CertA.csproj --no-build --verbosity normal

  build:
    runs-on: ubuntu-latest
    needs: test
    environment: public
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:main -f CertA/Dockerfile .

      - name: Push to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: public
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME }}:main

      - name: Deploy to Swarm
        run: |
          # Initialize swarm if not already initialized
          docker swarm init --advertise-addr 127.0.0.1 || true
          docker stack deploy -c docker-compose.swarm.yml certa

      - name: Wait for services
        run: sleep 30

      - name: Health check
        run: |
          # Get the node where the service is running
          SERVICE_NODE=$(docker stack ps certa --format "table {{.Node}}" | grep -v "NODE" | head -1)
          echo "Service node: $SERVICE_NODE"
          
          # Check if we got a valid node
          if [ -z "$SERVICE_NODE" ]; then
            echo "No service node found, checking localhost instead"
            curl -f http://localhost:8080
          else
            curl -f http://$SERVICE_NODE:8080
          fi

      - name: Show deployment status
        run: docker stack services certa
