name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Generate changelog
      id: changelog
      uses: actions/github-script@v7
      with:
        script: |
          const { data: commits } = await github.rest.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: 'main',
            head: context.sha
          });
          
          const changelog = commits.commits
            .map(commit => `- ${commit.commit.message}`)
            .join('\n');
          
          core.setOutput('changelog', changelog);
          
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: CertA ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## What's Changed
          
          ${{ steps.changelog.outputs.changelog }}
          
          ## Docker Image
          
          The Docker image is available at: `judyandiealvarez/certa:${{ steps.get_version.outputs.VERSION }}`
          
          ## Quick Start
          
          ```bash
          docker run -d -p 8080:8080 judyandiealvarez/certa:${{ steps.get_version.outputs.VERSION }}
          ```
          
          ## Documentation
          
          See the [documentation](https://github.com/judyandiealvarez/CertA/tree/main/docs) for detailed setup and usage instructions.
        draft: false
        prerelease: false
